name: Build and Upload Resource Pack

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive Resource Pack
        run: |
          # Create a zip file of your resource pack
          zip -r resource_pack.zip <path-to-resource-pack-directory>

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: resource-pack
          path: resource_pack.zip
