name: Minecraft Resource Pack Build

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Archive Resource Pack
      run: |
        zip -r resource_pack.zip assets/

    - name: Create Release & Upload Assets
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: resource-pack-build-${{ github.run_number }}.zip
        tag_name: build-${{ github.run_number }}
        name: resource-pack.zip
