name: Minecraft Resource Pack Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build resource pack
      run: |
        # Add build commands here to manipulate your resource pack assets
        # For example:
        # - Convert textures to the desired format
        # - Optimize file sizes
        # - Apply modifications to the assets
        
        # This command simply lists the contents of the assets folder
        ls assets/

    - name: Archive resource pack
      run: |
        # Compress the resource pack into a ZIP file
        zip -r resource_pack.zip assets/

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: resource-pack
        path: resource_pack.zip
