name: Minecraft Resource Pack Build

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Archive Resource Pack
      run: |
        zip -r resource_pack.zip assets/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: resource-pack
        path: resource_pack.zip
